### ISSUE TITLE
Can't locate Test/Authorization.pm in @INC

### ISSUE THREAD

**Issue by eserte** [Humanstate/api-client-public-module#4] opened 2023-11-18 09:11 UTC
t/payprop/api/public/client/authorization/base.t may fail, probably due to a missing prereq specification:
```
#   Failed test 'use Test::Authorization;'
#   at t/payprop/api/public/client/authorization/base.t line 20.
#     Tried to use 'Test::Authorization'.
#     Error:  Can't locate Test/Authorization.pm in @INC (you may need to install the Test::Authorization module) (@INC contains: ...  .) at t/payprop/api/public/client/authorization/base.t line 20.
# BEGIN failed--compilation aborted at t/payprop/api/public/client/authorization/base.t line 20.
# Looks like you failed 1 test of 4.
```

**Comment by ghost** [comment] 2023-11-28 10:12
Can't reproduce on my side
```
prove -lrv t/payprop/api/public/client/authorization/base.t
t/payprop/api/public/client/authorization/base.t ..
# The request methods are tested in respective consumer classes e.g. t/unit/payprop/api/public/client/authorization/clientcredentials.t
ok 1 - use Test::Authorization;
ok 2 - An object of class 'Test::Authorization' isa 'Test::Authorization'
ok 3 - Test::Authorization->can(...)
ok 4 - threw Regexp ((?^:_token_request_p not implemented))
1..4
ok
All tests successful.
Files=1, Tests=4,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.10 cusr  0.01 csys =  0.12 CPU)
Result: PASS
```

**Comment by vskrupskis** [comment] 2023-11-28 10:13
I'll close this one off for now as I can't reproduce.

**Comment by ghost** [comment] 2023-11-28 10:14
I'll close this one off for now as I can't reproduce.

**Closed as not planned by ghost** 2023-11-28 10:14 UTC

**Comment by eserte** [comment] 2023-11-28 19:11
@vskrupskis Feel free. However http://matrix.cpantesters.org/?dist=PayProp-API-Public-Client+0.03 shows quite a number of fail reports. Unfortunately there seems to be different cases for these, so statistical analysis does not help here.
